# Generated by Django 4.2.4 on 2023-08-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=122)),
                ('LastName', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Address', models.CharField(max_length=122)),
                ('PaymentMethod', models.CharField(max_length=122)),
            ],
        ),
    ]
