# Generated by Django 4.2.4 on 2023-08-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iphone', models.CharField(max_length=60)),
                ('Space', models.CharField(max_length=60)),
                ('Price', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
